[tox]
envlist = flake8, pylint, tests

[testenv]
basepython=pypy3

[testenv:flake8]
commands = flake8 setup.py powny tests
deps =
    flake8
    flake8-double-quotes
    pytest
    pytest-localserver

[testenv:pylint]
commands = pylint --output-format=colorized --reports=no setup.py powny tests
deps =
    pylint
    pytest
    pytest-localserver

[testenv:tests]
commands = py.test -vv --cov powny --no-cov-on-fail --cov-report term-missing
deps =
    pytest
    pytest-cov
    pytest-localserver
    coveralls

[flake8]
# W503 line break before binary operator
ignore=W503
max-line-length = 120
